apiVersion: app.m4d.ibm.com/v1alpha1
kind: M4DApplication
metadata:
  name: hw-module-test
spec:
  selector:
   workloadSelector:
     matchLabels: {}
  appInfo:
    purpose: Fraud Detection
    role: Data Owner
  data:
    - dataSetID: "{\"ServerName\":\"cocoMDS3\",\"AssetGuid\":\"ASSET_ID\"}" 
      requirements:
        copy:
          required: true
        interface:
          protocol: m4d-arrow-flight
          dataformat: parquet